# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=250)),
                ('published', models.DateField(default=datetime.datetime(2017, 8, 21, 13, 4, 18, 708373, tzinfo=utc))),
                ('last_modified', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
