# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
